# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "UILiteX"
license = "MIT"
licenselink = "https://github.com/skmatz/hugo-uilitex/blob/master/LICENSE"
description = "Customized UILite Theme for Hugo"
homepage = "https://github.com/skmatz/hugo-uilitex"
tags = ["portfolio"]
features = ["portfolio"]
min_version = "0.41"

[author]
  name = "Shunta Komatsu"
  homepage = "https://github.com/skmatz"
